Factory/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models
{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {

    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int EngineerId { get; set; }
    public string EngName { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models
{
  public class EngineerMachine
  {
    public int EngineerId { get; set; }
    public int MachineId { get; set; }
    public int EngineerMachineId { get; set; }
    public virtual Engineer Engineer { get; set; }
    public virtual Machine Machine { get; set; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public virtual DbSet<Machine> Machines { get; set; }
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<EngineerMachine> EngineerMachine { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int MachineId { get; set; }
    public string MachName { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;
    public EngineersController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachName");
      return View();
    }
    [HttpPost]
    public ActionResult Create(Engineer engineer, int MachineId)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
      .Include(engineer => engineer.JoinEntities)
      .ThenInclude(join => join.Machine)
      .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }
    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachName");
      return View(thisEngineer);
    }
    [HttpPost]
    public ActionResult Edit(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(item => item.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachName");
      return View(thisEngineer);
    }
    [HttpPost]
    public ActionResult AddMachine(Engineer item, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = item.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Factory.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Factory.Models;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
      .Include(machine => machine.JoinEntities)
      .ThenInclude(join => join.Engineer)
      .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }
    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer
<div class="mainCont">
  <div class="head">
    <h1>Register a Machine to @Html.DisplayFor(model => model.EngName)</h1>
  </div>
  @using (Html.BeginForm())
  {
    <div class="content">
      @Html.HiddenFor(model => model.EngineerId)

      @Html.Label("Select Machine")
      @Html.DropDownList("MachineId")
      <div class="back">
        <input type="submit" value="Save" />
      </div>
    </div>
  }
  <div class="back">
    <p>@Html.ActionLink("Back to Engineers List", "Index")</p>
  </div>
</div>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Engineer
<div class="mainCont">
  <div class="head">
    <h1>Add a new Engineer to our Factory roster!</h1>
  </div>
  @using (Html.BeginForm())
  {
    <div class="content">
      <p>@Html.Label("Engineer Name:")
        @Html.TextBoxFor(model => model.EngName, new { @required="required" })</p>

      <div class="back">
        <input type="submit" value="Confirm" class="btn btn-default">
      </div>
    </div>
  }

  <div class="back">
    <p>@Html.ActionLink("Back to List of Engineers", "Index")</p>
  </div>
</div>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Engineer
<div class="mainCont">
  <div class="head">
    <h1>Delete Engineer!</h1>
  </div>
  <div class="content">
    <p>Are you sure you want to delete poor @Html.DisplayFor(model => model.EngName)?</p>
    @using (Html.BeginForm())
    {
      <input type="submit" value="Delete" class="btn btn-default">
    }
  </div>
  <div class="back">
    <p>@Html.ActionLink("Back to List of Engineers", "Index")</p>
  </div>
</div>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Engineer
<div class="mainCont">
  <div class="head">
    <h1>Engineer Profile for @Html.DisplayFor(model => model.EngName):</h1>
  </div>
  <div class="content">
    <h3>@Html.DisplayFor(model => model.EngName)</h3>
    @if (@Model.JoinEntities.Count == 0)
    {
      <p>This Engineer is not currently available to work on any Machines :(</p>
    }
    else
    {
      <p>This Engineer is able to repair the following machines:</p>
      <ul>
        @foreach (var join in Model.JoinEntities)
        {
          <li>@join.Machine.MachName</li>
          @using (Html.BeginForm("DeleteMachine", "Engineers"))
          {
            @Html.Hidden("joinId", @join.EngineerMachineId)
            <div class="back">
              <input type="submit" value="Delete" class="btn btn-default">
            </div>
          }
        }
      </ul>
    }
  </div>
  <div class="back">
    <p>@Html.ActionLink("Register Machine for this Engineer", "AddMachine", new { id = Model.EngineerId })</p>
    <p>@Html.ActionLink("Edit this Engineer", "Edit", new { id = Model.EngineerId })</p>
    <p>@Html.ActionLink("Delete this Engineer", "Delete", new { id = Model.EngineerId })</p>
    <p>@Html.ActionLink("Back to our Engineers List", "Index")</p>
  </div>
</div>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer
<div class="mainCont">
  <div class="head">
    <h1>Edit</h1>
  </div>
  <div class="content">
    <p>Edit Engineer: @Html.DisplayFor(model => model.EngName)</p>
    @using (Html.BeginForm())
    {
      @Html.HiddenFor(model => model.EngineerId)
      <p>Name:
        @Html.TextBoxFor(model => model.EngName, new { @required="required" })</p>
      @Html.Label("Add new Machine")
      @Html.DropDownList("MachineId")
      <input type="submit" value="Save" class="btn btn-default">
    }
  </div>
  <div class="back">
    <p>@Html.ActionLink("Back to List of our Engineers", "Index")</p>
  </div>
</div>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Engineer>;
<div class="mainCont">
  <div class="head">
    <h1>We most definitely ONLY employ the FINEST, most SKILLED ENGINEERS in all of the land...</h1>
  </div>
  <div class="content">
    @if (@Model.Count == 0)
    {
      <p>No Engineers yet, woopsies!!</p>
    }
    <div class="subhead">
      <h3>Browse our current Engineers:</h3>
    </div>
    @foreach (Engineer engineer in Model)
    {
      <div class="listo">
        <li>@Html.ActionLink($"{engineer.EngName}", "Details", new { id = engineer.EngineerId })</li>
      </div>
    }
    <div class="create">
      <h3>Missing Someone?</h3>
      <div class="c-link">
        <p>@Html.ActionLink("HIRE a new ENGINEER", "Create")</p>
      </div>
    </div>
  </div>
</div>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}



<h1 class="content">WELCOME to Dr. SilLyStRInGZ's FACTORY</h1>
<h3 class="content">Use the menu to browse an impressive collection of cool machines and talented engineers...</h3>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Machine
<div class="mainCont">
  <div class="head">
    <h1>Install a new Machine:</h1>
  </div>
  @using (Html.BeginForm())
  {
    <div class="content">
      <p>@Html.Label("Enter new Machine Name:")
        @Html.TextBoxFor(model => model.MachName, new { @required="required" })</p>
      <div class="back">
        <input type="submit" value="Install new Machine" class="btn btn-default">
      </div>
    </div>
  }
  <div class="back">
    <p>@Html.ActionLink("Back to all Machines", "Index")</p>
  </div>
</div>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Machine
<div class="mainCont">
  <div class="head">
    <h1>Delete This Machine</h1>
  </div>
  <div class="content">
    <p>Are you TOTALLY sure you want to delete @Html.DisplayFor(model => model.MachName)?</p>
    @using (Html.BeginForm())
    {
      <input type="submit" value="Delete" class="btn btn-default">
    }
  </div>
  <div class="back">
    @Html.ActionLink("Back to the List", "Index")
  </div>
</div>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Machine;
<div class="mainCont">
  <div class="head">
    <h1>Details regarding the: @Html.DisplayFor(model => model.MachName)</h1>
  </div>
  <div class="content">
    <p>Machine Name: @Html.DisplayFor(model => model.MachName)</p>
    @if (@Model.JoinEntities.Count == 0)
    {
      <div class="back">
        <p>No Engineers are currently able to work on this Machine, Woopsies!</p>
      </div>
    }
    else
    {
      <div class="back">
        <p>Engineers available to work on this Machine:</p>
      </div>
      <ul>
        @foreach (var join in Model.JoinEntities)
        {
          <div class="back">
            <li>@join.Engineer.EngName</li>
          </div>
        }
      </ul>
    }
  </div>
  <div class="back">
    <p>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId })</p>
    <p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>
    <p>@Html.ActionLink("Back to list of all Machines", "Index")</p>
  </div>
</div>
</div>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Machine
<div class="mainCont">
  <div class="head">
    <h1>Edit</h1>
  </div>
  <div class="content">
    <p>Edit @Html.DisplayFor(model => model.MachName)?</p>
    @using (Html.BeginForm())
    {
      @Html.HiddenFor(model => model.MachineId)
      <p>Name:
        @Html.TextBoxFor(model => model.MachName, new { @required="required" })</p>
      <input type="submit" value="Save" class="btn btn-default">
    }
  </div>
  <div class="back">
    @Html.ActionLink("Back", "Index")
  </div>
</div>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;
<div class="mainCont">
  <div class="head">
    <h1>All of our MACHINES are very RELIABLE, and incredibly PRODUCTIVE </h1>
  </div>
  <div class="content">
    @if (@Model.Count == 0)
    {
      <p>No Machines yet, woopsies!!</p>
    }
    else
    {
      <div class="subhead">
        <h3>Feast your eyes on these machines:</h3>
      </div>
    }
    @foreach (Machine machine in Model)
    {
      <div class="listo">
        <li>@Html.ActionLink($"{machine.MachName}", "Details", new { id = machine.MachineId })</li>
      </div>
    }
    <div class="create">
      <h3>Missing Something..?</h3>
      <div class="c-link">
        <p>@Html.ActionLink("BUY a new MACHINE", "Create")</p>
      </div>
    </div>
  </div>
</div>

Factory/Views/Shared/_Footer.cshtml
<div id="footer">
  <p>Thank you so much for visiting the factory.</p>
</div>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>DR SILLYSTRINGZ FACTORY</title>
  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
  <link rel="stylesheet" href="~/css/styles.css">
</head>

<body>
  <div class="container">
    @Html.Partial("_Sidebar")
    @RenderBody()
    @Html.Partial("_Footer")
  </div>
</body>

</html>

Factory/Views/Shared/_Sidebar.cshtml
<div class="sidenav">
  <a href="#">@Html.ActionLink("ENGINEERS", "Index", "Engineers")</a>
  <a href="#">@Html.ActionLink("MACHINES", "Index", "Machines")</a>
  <a href="#">@Html.ActionLink("Home", "Index", "Home")</a>
</div>